package dto_dao;

public class DTO_ORDERS {
	private String PRODUCTORDERSCODE;
	private String PRODUCTCODE;
	private String USERID;
	private String ORDERSNAME;
	private String FRODUCTNAME;
	private String ORDERQNANTITY;
	private String FORDUCTPRICE;
	private String RECIPIENTNAME;
	private String RECIPIENTPHONE;
	private String SHIPPINGADDRESS;
	private String FORWARDINGMESSAGEINABSENCE;
	private String PAYMENTMETHOD;
	private String PAYMENTTIME;
	private String PRODUCT_OPTION;
	
	public DTO_ORDERS() {};
	
	public DTO_ORDERS(String pRODUCTCODE, String uSERID, String oRDERSNAME,
			String fRODUCTNAME, String oRDERQNANTITY, String fORDUCTPRICE, String rECIPIENTNAME, String rECIPIENTPHONE,
			String sHIPPINGADDRESS, String fORWARDINGMESSAGEINABSENCE, String pAYMENTMETHOD, String pRODUCT_OPTION) {
		PRODUCTCODE = pRODUCTCODE;
		USERID = uSERID;
		ORDERSNAME = oRDERSNAME;
		FRODUCTNAME = fRODUCTNAME;
		ORDERQNANTITY = oRDERQNANTITY;
		FORDUCTPRICE = fORDUCTPRICE;
		RECIPIENTNAME = rECIPIENTNAME;
		RECIPIENTPHONE = rECIPIENTPHONE;
		SHIPPINGADDRESS = sHIPPINGADDRESS;
		FORWARDINGMESSAGEINABSENCE = fORWARDINGMESSAGEINABSENCE;
		PAYMENTMETHOD = pAYMENTMETHOD;
		PRODUCT_OPTION = pRODUCT_OPTION;
	}



	public DTO_ORDERS(String pRODUCTORDERSCODE, String pRODUCTCODE, String uSERID, String oRDERSNAME,
			String fRODUCTNAME, String oRDERQNANTITY, String fORDUCTPRICE, String rECIPIENTNAME, String rECIPIENTPHONE,
			String sHIPPINGADDRESS, String fORWARDINGMESSAGEINABSENCE, String pAYMENTMETHOD, String pAYMENTTIME,
			String pRODUCT_OPTION) {
		PRODUCTORDERSCODE = pRODUCTORDERSCODE;
		PRODUCTCODE = pRODUCTCODE;
		USERID = uSERID;
		ORDERSNAME = oRDERSNAME;
		FRODUCTNAME = fRODUCTNAME;
		ORDERQNANTITY = oRDERQNANTITY;
		FORDUCTPRICE = fORDUCTPRICE;
		RECIPIENTNAME = rECIPIENTNAME;
		RECIPIENTPHONE = rECIPIENTPHONE;
		SHIPPINGADDRESS = sHIPPINGADDRESS;
		FORWARDINGMESSAGEINABSENCE = fORWARDINGMESSAGEINABSENCE;
		PAYMENTMETHOD = pAYMENTMETHOD;
		PAYMENTTIME = pAYMENTTIME;
		PRODUCT_OPTION = pRODUCT_OPTION;
	}
	
	public String getPRODUCTORDERSCODE() {
		return PRODUCTORDERSCODE;
	}
	public void setPRODUCTORDERSCODE(String pRODUCTORDERSCODE) {
		PRODUCTORDERSCODE = pRODUCTORDERSCODE;
	}
	public String getPRODUCTCODE() {
		return PRODUCTCODE;
	}
	public void setPRODUCTCODE(String pRODUCTCODE) {
		PRODUCTCODE = pRODUCTCODE;
	}
	public String getUSERID() {
		return USERID;
	}
	public void setUSERID(String uSERID) {
		USERID = uSERID;
	}
	public String getORDERSNAME() {
		return ORDERSNAME;
	}
	public void setORDERSNAME(String oRDERSNAME) {
		ORDERSNAME = oRDERSNAME;
	}
	public String getFRODUCTNAME() {
		return FRODUCTNAME;
	}
	public void setFRODUCTNAME(String fRODUCTNAME) {
		FRODUCTNAME = fRODUCTNAME;
	}
	public String getORDERQNANTITY() {
		return ORDERQNANTITY;
	}
	public void setORDERQNANTITY(String oRDERQNANTITY) {
		ORDERQNANTITY = oRDERQNANTITY;
	}
	public String getFORDUCTPRICE() {
		return FORDUCTPRICE;
	}
	public void setFORDUCTPRICE(String fORDUCTPRICE) {
		FORDUCTPRICE = fORDUCTPRICE;
	}
	public String getRECIPIENTNAME() {
		return RECIPIENTNAME;
	}
	public void setRECIPIENTNAME(String rECIPIENTNAME) {
		RECIPIENTNAME = rECIPIENTNAME;
	}
	public String getRECIPIENTPHONE() {
		return RECIPIENTPHONE;
	}
	public void setRECIPIENTPHONE(String rECIPIENTPHONE) {
		RECIPIENTPHONE = rECIPIENTPHONE;
	}
	public String getSHIPPINGADDRESS() {
		return SHIPPINGADDRESS;
	}
	public void setSHIPPINGADDRESS(String sHIPPINGADDRESS) {
		SHIPPINGADDRESS = sHIPPINGADDRESS;
	}
	public String getFORWARDINGMESSAGEINABSENCE() {
		return FORWARDINGMESSAGEINABSENCE;
	}
	public void setFORWARDINGMESSAGEINABSENCE(String fORWARDINGMESSAGEINABSENCE) {
		FORWARDINGMESSAGEINABSENCE = fORWARDINGMESSAGEINABSENCE;
	}
	public String getPAYMENTMETHOD() {
		return PAYMENTMETHOD;
	}
	public void setPAYMENTMETHOD(String pAYMENTMETHOD) {
		PAYMENTMETHOD = pAYMENTMETHOD;
	}
	public String getPAYMENTTIME() {
		return PAYMENTTIME;
	}
	public void setPAYMENTTIME(String pAYMENTTIME) {
		PAYMENTTIME = pAYMENTTIME;
	}

	public String getPRODUCT_OPTION() {
		return PRODUCT_OPTION;
	}

	public void setPRODUCT_OPTION(String pRODUCT_OPTION) {
		PRODUCT_OPTION = pRODUCT_OPTION;
	}
	
	
}
